image: quay.io/fenicsproject/dev

pipelines:
  default:
    - step:
        script:
          - pip2 install --no-cache-dir --upgrade pytest
          - export CC=mpicc
          - export HDF5_MPI=ON
          - pip2 install --no-binary ":all:" --no-cache-dir h5py
          - export HOME=/home/fenics
          - export FENICS_PREFIX=$HOME/local
          - export FENICS_PYTHON_MAJOR_VERSION=2
          - export FENICS_PYTHON_MINOR_VERSION=7
          - source /home/fenics/.profile
          - cd $BITBUCKET_CLONE_DIR
          - export PYTHONPATH=$PWD:$PYTHONPATH
          - mpiexec -n 2 python2 -m pytest -v .

