image: firedrakeproject/firedrake

pipelines:
  default:
    - step:
        script:
          - source /home/firedrake/firedrake/bin/activate
          - export HOME=/home/firedrake
          - cd $BITBUCKET_CLONE_DIR
          - pip install .
          - mpiexec -n 2 python -m pytest -x -v defcon/ examples/firedrake/
