image: firedrakeproject/firedrake

test: &test
  step:
    name: Run the unit tests
    max-time: 30
    script:
      - source /home/firedrake/firedrake/bin/activate
      - pip install pybadges
      - export HOME=/home/firedrake
      - python -m pybadges --left-text=pipelines --right-text=failure --right-color='#c00' > status.svg
      - cd $BITBUCKET_CLONE_DIR
      - pip install .
      - pip install pytest-timeout
      - mpiexec -n 1 python -m pytest -v -s --timeout=600 --timeout-method=thread -o faulthandler_timeout=660 examples/firedrake/poisson/  # JIT deadlocks with 2 cores?!
      - mpiexec -n 2 python -m pytest -v -s --timeout=600 --timeout-method=thread -o faulthandler_timeout=660 defcon/ examples/firedrake/
      - cd -
      - python -m pybadges --left-text=pipelines --right-text=success --right-color='#0c0' > status.svg
    artifacts:
      - status.svg

upload-badge: &upload-badge
  step:
    name: Upload the build status
    script:
      - pipe: atlassian/bitbucket-upload-file:0.1.8
        variables:
          BITBUCKET_USERNAME: $BITBUCKET_USERNAME
          BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
          FILENAME: 'status.svg'

docker: &docker
  - step:
      name: Build Docker image
      script:
        - IMAGE_NAME=$BITBUCKET_REPO_SLUG
        - docker build . --file docker/Dockerfile --tag ${IMAGE_NAME}
        - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
      services:
        - docker
      caches:
        - docker
      artifacts:
        - "*.tar"
  - step:
      name: Upload Docker image
      deployment: Production
      script:
        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        - IMAGE_NAME=$BITBUCKET_REPO_SLUG
        - docker load --input "${IMAGE_NAME}.tar"
        - VERSION="latest"
        - IMAGE=${DOCKERHUB_USERNAME}/${IMAGE_NAME}
        - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
        - docker push "${IMAGE}:${VERSION}"
      services:
        - docker

pipelines:
  default:
    - <<: *test
  branches:
    master:
    - <<: *test
    - <<: *upload-badge
    - <<: *docker
    jackbetteridge/docker_ci:
    - <<: *test
    - <<: *upload-badge
    - <<: *docker
